### ISSUE TITLE
Include Session ID in file download

### ISSUE THREAD

**Issue by brianwarehime** [micheloosterhof/kippo#10]
Michel,

Not sure if this falls in with your efforts, but, since your project is updated more frequently than desaster's, figured I'd post it here.

Currently, when a user downloads a file, the logs get outputted into kippo.log like the below:

2015-02-16 09:00:19-0500 [HTTPPageDownloader,client] SHA sum 574345fa836eca70c776687c1bab659c2fbc899323c2a84882c0e5cc4d2560d4 of URL http://geoff.altervista.org/gosh.tgz in file dl/20150216090018_http___geoff_altervista_org_gosh_tgz

Is there a way to include the session ID or the source IP address like the other events into this field, since there is no context of what session this was done or what the source IP was. Any help would be great. This is just for the standard Kippo logging, and not the JSON output or textlog.

Thanks!

**Comment by micheloosterhof** [comment]
Hi Brian,

I understand your question. This issue is caused by the Twisted logging framework switching context and getting a different log prefix, when downloading your log prefix is for the HTTP reactor, no longer for the main Kippo reactor.

An easy workaround is to fetch this information from the 'dblog' subsystem. This actually works correctly, since it contains code to workaround this issue. Any dblog subsystem will work, either TextLog, JSON, MySQL, etc. Textlog will probably be best in your case.

I am working on an improved logging subsystem, and this will probably solve your issue, but right now the above is probably your best workaround.

**Comment by micheloosterhof** [comment]
I won't change this in the default logging output, I suggest you use one of the alternate logging outputs for this.
